config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :teams do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :notifications, only: [:index, :destroy]
  resources :users
  get 'unsubscribe/user' => 'users#unsubscribe', as: 'unsubscribe_user'
  patch ':withdraw/user' => 'users#withdraw', as: 'withdraw_user'
  get 'inquiry/index'
  post 'inquiry/confirm'
  post 'inquiry/thanks'
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :sports do
    resource :favorites, only: [:create, :destroy]
  end
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'user/following/:id' => 'users#following', as: 'following'
  get 'user/follower/:id' => 'users#follower', as: 'follower'
  get 'tags/:tag_name' => 'tags#index', as: 'tags'

end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :teams
  has_many :tags, dependent: :destroy
  attachment :image
  validates :name, length: { maximum: 20, minimum: 2 }, uniqueness: true
  validates :introduction, length: { maximum: 500 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @sports = Sport.where(is_active: true).order(:name)
    @sport = Sport.new
  end

  def create
    @sport = Sport.new(sport_params)
    if @sport.save
      @tags = Vision.get_image_data(@sport.image)
      @tags.each do |tag|
        @sport.tags.create(name: tag)
      end
      redirect_to sports_path, notice: "ベンチャースポーツを作成しました。"
    else
      @sports = Sport.all
      render "index"
    end
  end

  def show
    @sports = Sport.where(is_active: true)
    @sport = Sport.find(params[:id])
  end

  def edit
    @sport = Sport.find(params[:id])
  end

  def update
    @sport = Sport.find(params[:id])
    if @sport.update(sport_params)
      redirect_to sports_path, notice: "ベンチャースポーツを更新しました。"
    else
      render "edit"
    end
  end
  
  def destroy
    @sport = Sport.find(params[:id])
    @sport.destroy
    flash[:notice] = "ベンチャースポーツを削除しました。"
    redirect_to sports_path
  end

  private
  def sport_params
    params.require(:sport).permit(:image, :user_id, :name, :is_active, :introduction)
  end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_with model: sport, url: sports_path, local: true do |f| %>
  <div class="font-weight-bold mt-5">イメージ</div>
    <%= f.attachment_field :image %>
  <div class="font-weight-bold mt-5">ベンチャースポーツ名</div>
    <%= f.text_field :name, class:'form-control' %>
  <div class="font-weight-bold mt-5">概要</div>
    <%= f.text_area :introduction, class:'form-control' %>
  <div class="form_action text-center mt-4">
    <%= f.submit "登録", class:'btn btn-outline-info' %>
  </div>
<% end %>

app/views/sports/_sport_list.html.erb
<div class="col-3 card shadow-ig py-3 px-2 text-center">
  <div class="sport-sport"><%= link_to sport_path(sport) do %><%= attachment_image_tag sport, :image, size: "150x150", fallback: "no_image.jpg" %><% end %></div>
  <h4 class="sport-name my-3"><%= link_to sport.name, sport_path(sport) %></h4>
  <% sport.tags.each do |tag| %>
    <div class="">
      <%= link_to tags_path(tag.name), class: 'btn btn-outline-info m-1 p-1' do %>
        <%= tag.name %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/sports/edit.html.erb
<%= render 'layouts/error_messages', model: @sport %>
<div class="row">
  <div class="col-md-12 text-center">
    <i class="far fa-edit fa-3x mt-4 mb-2"></i>
    <h2><%= @sport.name %>の情報編集</h2>
    <%= form_with model: @sport, url: sport_path, local:true do |f| %>
      <%= attachment_image_tag @team, :image, :fill, 150, 150, fallback: "no_image.jpg"%><br>
      <%= f.attachment_field :image, placeholder: "イメージ" %><br>
      <div class="font-weight-bold mt-5">
        <label>ベンチャースポーツ名</label>
        <%= f.text_field :name, class:"form-control" %>
      </div>
      <div class="font-weight-bold mt-5">
        <label>概要</label>
        <%= f.text_area :introduction, class:"form-control" %>
      </div>
      <div class="actions mt-5">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/sports/index.html.erb
<%= render 'layouts/error_messages', model: @sport %>
<div class="row">
  <div class="col-12 text-center">
    <i class="fas fa-passport fa-3x mt-4 mb-2"></i>
    <h2 class="text-center bg-gray">ベンチャースポーツ一覧</h2>
    <% if user_signed_in? %>
      <div class="form_action text-center">
        <%= link_to 'ベンチャースポーツ登録', sports_path(anchor: 'v_form'), class:'btn btn-outline-info my-3' %>
      </div>
    <% end %>
  </div>
</div>
<% if @sports.present? %>
  <div class="row">
    <% @sports.each do |sport| %>
      <%= render 'sports/sport_list', sport: sport ,tag: tag %>
    <% end %>
</div>
<% else %>
  <div class="col-12 text-center">
    <i class="fas fa-exclamation fa-2x mt-4 text-center"></i>
    <p class="mt-2 text-center">ベンチャースポーツがありません。</p>
  </div>
<% end %>
<% if user_signed_in? %>
  <div class="row mt-5">
    <div class="col-12 text-center">
      <i class="fas fa-plus fa-3x mt-4 mb-2" id="v_form"></i>
      <h2 class="text-center bg-gray">ベンチャースポーツ登録</h2>
      <%= render 'sports/form', sport: @sport %>
    </div>
  </div>
<% end %>

app/views/sports/show.html.erb
<div class="row">
  <div class="col-12 text-center">
    <i class="fas fa-passport fa-3x mt-4 mb-2"></i>
    <h2>ベンチャースポーツ詳細</h2>
    <table class="table">
      <tbody>
        <tr>
          <%= attachment_image_tag @sport, :image, :fill, 150, 150, fallback: "no_image.jpg", size:'150x150' %>
        </tr>
        <tr>
          <th><label>ベンチャースポーツ名</label></th>
          <td><%= @sport.name %></td>
        </tr>
        <tr>
          <th><label>概要</label></th>
          <td><%= @sport.introduction %></td>
        </tr>
      </tbody>
    </table>
    <% if user_signed_in? %>
      <%= link_to "編集する", edit_sport_path(@sport), class: "btn btn-outline-info text-center"%>
    <% end %>
  </div>
</div>