config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :teams do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :notifications, only: [:index, :destroy]
  resources :users
  get 'unsubscribe/user' => 'users#unsubscribe', as: 'unsubscribe_user'
  patch ':withdraw/user' => 'users#withdraw', as: 'withdraw_user'
  get 'inquiry/index'
  post 'inquiry/confirm'
  post 'inquiry/thanks'
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :sports do
    resource :favorites, only: [:create, :destroy]
  end
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'user/following/:id' => 'users#following', as: 'following'
  get 'user/follower/:id' => 'users#follower', as: 'follower'
  get 'tags/:tag_name' => 'tags#index', as: 'tags'

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  
  def follow
    @user = User.find(params[:id])
    current_user.follow(params[:id])
    @user.create_notification_follow!(current_user)
    render :create
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.unfollow(params[:id])
    render :destroy
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_form.html.erb
<div id="follow_form">
  <% if current_user.following?(user) %>
    <%= link_to unfollow_path(user.id), method: :POST, remote: true do %>
      <i class="fas fa-user-slash fa-2x", data-toggle="tooltip", data-placement="bottom", title="フォローを外す"></i>
    <% end %>
  <% else %>
    <%= link_to follow_path(user.id), method: :POST, remote: true do %>
      <i class="fas fa-user-plus fa-2x", data-toggle="tooltip", data-placement="bottom", title="フォローする"></i>
    <% end %>
  <% end %>
</div>

app/views/relationships/create.js.erb
$('#follow_form_<%= @user.id %>').html("<%= j(render partial: 'relationships/follow_form', locals: {user: @user}) %>");

app/views/relationships/destroy.js.erb
$('#follow_form_<%= @user.id %>').html("<%= j(render partial: 'relationships/follow_form', locals: {user: @user}) %>");