config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :teams do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :notifications, only: [:index, :destroy]
  resources :users
  get 'unsubscribe/user' => 'users#unsubscribe', as: 'unsubscribe_user'
  patch ':withdraw/user' => 'users#withdraw', as: 'withdraw_user'
  get 'inquiry/index'
  post 'inquiry/confirm'
  post 'inquiry/thanks'
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :sports do
    resource :favorites, only: [:create, :destroy]
  end
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'user/following/:id' => 'users#following', as: 'following'
  get 'user/follower/:id' => 'users#follower', as: 'follower'
  get 'tags/:tag_name' => 'tags#index', as: 'tags'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  has_many :teams, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :sns_credentials, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  attachment :profile_image

  validates :email, presence: true, uniqueness: true
  validates :handle_name, length: { maximum: 20, minimum: 2 }, uniqueness: true
  validates :introduction, length: { maximum: 500 }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.handle_name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  paginates_per 10
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    # 先ほどuser.rbで記述したメソッド(from_omniauth)をここで使っています
    # 'request.env["omniauth.auth"]'この中にgoogoleアカウントから取得したメールアドレスや、名前と言ったデータが含まれています
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user, event: :authentication
    set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
  end

  def failure
    redirect_to root_path
  end

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

 password = Devise.friendly_token.first(7)
  if session[:provider].present? && session[:uid].present?
    @user = User.create(handle_name:session[:handle_name], email: session[:email], password: "password", password_confirmation: "password")
    sns = SnsCredential.create(user_id: @user.id,uid: session[:uid], provider: session[:provider])
  else
    @user = User.create(handle_name:session[:handle_name], email: session[:email], password: session[:password], password_confirmation: session[:password_confirmation])
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  PER = 10

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(PER)
  end

  def show
    @user = User.find(params[:id])
    @team = @user.teams
    favorites = Favorite.where(user_id: current_user.id).pluck(:team_id)
    @favorite_list = Team.find(favorites)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to users_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "会員情報を更新しました。"
    else
      render :edit
    end
  end

  def unsubscribe
    @user = User.find_by(params[:id])
  end

  def withdraw
    @user = current_user
    if @user.update(is_deleted: true)
      reset_session
      redirect_to root_path, notice: "退会処理が完了しました。"
    else
      render :edit
    end
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following_user.page(params[:page]).per(PER)
  end

  def follower
    @user = User.find(params[:id])
    @users = @user.follower_user.page(params[:page]).per(PER)
  end

  private
  def user_params
    params.require(:user).permit(:id, :profile_image, :email, :last_name, :first_name, :kana_last_name, :kana_first_name, :handle_name, :postcode, :address, :phone_number, :is_deleted, :prefecture_code, :address_city, :address_street, :address_building, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_search_user.html.erb
<%= search_form_for q do |f| %>
  <%= f.search_field :handle_name_or_introduction_cont, placeholder: "キーワード", class:"my-4" %>
  <%= f.submit "検索" %>
<% end %>

app/views/users/_user_list.html.erb
<div class="card mb-2">
  <div class="row no-gutters">
    <div class="col-md-3 my-3">
      <%= link_to user_path(user) do %>
        <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %><br><%= user.handle_name %>
      <% end %>
    </div>
    <div class="col-md-6">
      <div class="card-body">
        <p><%= user.introduction %></p>
      </div>
    </div>
    <div class="col-md-1 my-3" id="follow_form_<%= user.id %>">
      <% unless user == current_user %>
        <%= render 'relationships/follow_form', user: user %>
      <% end %>
    </div>
    <div class="col-md-2 my-3">
      <%= link_to chat_path(user.id) do %>
        <i class="fas fa-envelope fa-2x m-1", data-toggle="tooltip", data-placement="bottom", title="メッセージ"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'layouts/error_messages', model: @user %>
<div class="row">
  <div class="col-md-12 text-center">
    <i class="far fa-edit fa-3x mt-4 mb-2"></i>
    <h2><%= @user.handle_name %>さんの登録情報編集</h2>
    <div class="form-group">
      <%= form_with model: @user, local: true do |f| %>
        <div class="my-5">
          <label for="inputImage my-3">プロフィール画像</label><br>
          <%= attachment_image_tag @user, :profile_image, :fill, 150, 150, fallback: "no_image.jpg"%><br>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        </div>
        <div class="my-3">
          <label>ハンドルネーム</label><br>
          <%= f.text_field :handle_name, autofocus: true, autocomplete: "handle_name", class:"form-control" %>
        </div>
        <div class="my-3">
          <label>自己紹介</label><br>
          <%= f.text_field :introduction, autofocus: true, autocomplete: "introduction", class:"form-control" %>
        </div>
        <div class="my-3">
          <label>メールアドレス</label>
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control" %>
        </div>
        <div class="actions mt-5">
          <%= f.submit "保存", class:'btn btn-outline-info' %>
        </div>
        <div class="actions mt-5">
          <%= link_to '退会', unsubscribe_user_path(current_user.id), class:'btn btn-outline-info' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/follower.html.erb
<div class="row">
  <div class="col-12 text-center">
    <i class="fas fa-user-friends fa-3x mt-4 mb-2"></i>
    <h2 class="text-center bg-gray">フォロワー</h2>
    <% if @users.present? %>
      <% @users.each do |user| %>
        <%= render 'users/user_list', user: user %>
      <% end %>
      <%= paginate @users %>
    <% else %>
      <div class="col-12 text-center">
        <i class="fas fa-exclamation fa-2x mt-4 text-center"></i>
        <p class="mt-2 text-center">会員はいません。</p>
      </div>
    <% end %>
    <%= link_to "マイページ", user_path(current_user), class: 'btn btn-outline-info mt-3' %>
  </div>
</div>

app/views/users/following.html.erb
<div class="row">
  <div class="col-12 text-center">
    <i class="fas fa-user-friends fa-3x mt-4 mb-2"></i>
    <h2 class="text-center bg-gray">フォロー</h2>
    <% if @users.present? %>
      <% @users.each do |user| %>
        <%= render 'users/user_list', user: user %>
      <% end %>
      <%= paginate @users %>
    <% else %>
      <div class="col-12 text-center">
        <i class="fas fa-exclamation fa-2x mt-4 text-center"></i>
        <p class="mt-2 text-center">会員はいません。</p>
      </div>
    <% end %>
    <%= link_to "マイページ", user_path(current_user), class: 'btn btn-outline-info mt-3' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-12 text-center">
    <i class="fas fa-user-friends fa-3x mt-4 mb-2"></i>
    <h2 class="text-center bg-gray">会員一覧</h2>
    <%= render 'users/search_user', q: @q %>
    <% if @users.present? %>
      <% @users.each do |user| %>
        <%= render 'users/user_list', user: user %>
      <% end %>
      <%= paginate @users %>
    <% else %>
      <div class="col-12 text-center">
        <i class="fas fa-exclamation fa-2x mt-4 text-center"></i>
        <p class="mt-2 text-center">他に会員がいません。</p>
      </div>
    <% end %>
    <%= link_to "マイページ", user_path(current_user), class: 'btn btn-outline-info mt-3' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <i class="fas fa-address-card fa-3x mt-4 mb-2"></i>
    <h2><%= @user.handle_name %>さんのページ</h2>
    <table class="table">
      <tbody>
        <tr>
           <th><label>プロフィール画像</label></th>
           <td class="rounded-circle"><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'100x100' %></td>
        </tr>
        <tr>
          <th><label>ハンドルネーム</label></th>
          <td><%= @user.handle_name %></td>
        </tr>
        <tr>
          <th><label>自己紹介</label></th>
          <td><%= @user.introduction %></td>
        </tr>
        <tr>
          <th><label>メールアドレス</label></th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th><label>フォロー数</label></th>
          <td>
            <%= link_to following_path(@user.id) do %>
              <%= @user.follower.count %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th><label>フォロワー数</label></th>
          <td>
            <%= link_to follower_path(@user.id) do %>
              <%= @user.followed.count %>
            <% end %>
          </td>
        </tr>
      <% unless @user == current_user %>
        <tr>
          <th><label>フォロー</label></th>
          <td id="follow_form_<%= @user.id %>">
            <%= render 'relationships/follow_form', user: @user %>
          </td>
        </tr>
      <% end %>
      <% if current_user != @user %>
        <tr>
          <th><label>メッセージ</label></th>
          <td>
            <%= link_to chat_path(@user.id) do %>
              <i class="fas fa-envelope fa-2x m-1", data-toggle="tooltip", data-placement="bottom", title="メッセージ"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      <% if @user == current_user %>
        <tr>
          <th><label></label></th>
          <td>
            <%= link_to edit_user_path do %>
              <i class="fas fa-edit fa-2x m-1", data-toggle="tooltip", data-placement="bottom", title="編集"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>


<% if @user == current_user %>
  <div class="row">
    <div class="col-12 text-center">
      <i class="fas fa-search fa-3x mt-4 mb-2"></i>
      <h2 class="text-center bg-gray">ブックマークチーム</h2>
      <% if @favorite_list.present? %>
        <% @favorite_list.each do |team| %>
          <%= render 'teams/team_list', team: team %>
        <% end %>
      <% else %>
        <div class="col-12 text-center">
          <i class="fas fa-exclamation fa-2x mt-4 text-center"></i>
          <p class="mt-2 text-center">ブックマークはありません。</p>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <% if @team.present? %>
    <div class="row">
      <div class="col-12 text-center">
        <i class="fas fa-search fa-3x mt-4 mb-2"></i>
        <h2 class="text-center bg-gray"><%= @user.handle_name %>さんのチーム</h2>
        <% @team.each do |team| %>
          <%= render 'users/team_list', team: team %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/unsubscribe.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <i class="fas fa-exclamation fa-3x mt-4 mb-2"></i>
    <h2>退会ページ</h2>
    <h5 class="text-center">退会すると、会員登録情報やチーム情報が閲覧できなくなります。<br>
      退会する場合は、「退会する」をクリックしてください。
    </h5>
    <div class="actions mt-4 text-center">
      <%= link_to '退会しない', user_path(current_user.id), class:'btn btn-outline-primary'%><br>
    </div>
    <div class="actions mt-4 text-center">
      <%= link_to "退会する", withdraw_user_path(current_user.id), method: :patch, class:'btn btn-outline-danger mt-4 text-center'%>
    </div>
  </div>
</div>