config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :teams do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :notifications, only: [:index, :destroy]
  resources :users
  get 'unsubscribe/user' => 'users#unsubscribe', as: 'unsubscribe_user'
  patch ':withdraw/user' => 'users#withdraw', as: 'withdraw_user'
  get 'inquiry/index'
  post 'inquiry/confirm'
  post 'inquiry/thanks'
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :sports do
    resource :favorites, only: [:create, :destroy]
  end
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'user/following/:id' => 'users#following', as: 'following'
  get 'user/follower/:id' => 'users#follower', as: 'follower'
  get 'tags/:tag_name' => 'tags#index', as: 'tags'

end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  attr_accessor :name, :email, :message
  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  
  def index
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def thanks
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))    
    InquiryMailer.received_email(@inquiry).deliver
    render :action => 'thanks'
  end
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/views/inquiry/confirm.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>

<%= form_with model: @inquiry, url: inquiry_thanks_path, local: true do |f| %>
  <table class="table">
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :name %>
        <%= @inquiry.name %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @inquiry.email %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@inquiry.message) %>
      </td>
    </tr>
  </table>
  <%= f.submit '送信', :class => 'btn btn-primary' %>
<% end %>

app/views/inquiry/index.html.erb
<div class="row">
  <div class="col-12 text-center">
    <i class="fas fa-question-circle fa-3x mt-4 mb-2"></i>
    <h2 class="text-center bg-gray">お問い合わせ</h2>
    <%= form_with model: @inquiry, url: inquiry_confirm_path, local: true do |f| %>
      <% if @inquiry.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <strong>入力内容にエラーがあります</strong>
          <ul>
            <% @inquiry.errors.each do |attr, msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <table class="table">
        <tr>
          <th>名前<span class="text-danger">（必須）</span></th>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <th>メールアドレス<span class="text-danger">（必須）</span></th>
          <td><%= f.text_field :email %></td>
        </tr>
        <tr>
          <th>お問い合わせ内容</th>
          <td><%= f.text_area :message %></td>
        </tr>
      </table>
      <%= f.submit '確認', class: 'btn btn-primary text-center' %>
    <% end %>
  </div>
</div>

app/views/inquiry/thanks.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
<p>
  お問い合わせいただきありがとうございました。
</p>